# Maaz Ali Nadeem - i200452 - BS AI J

## Machine Learning - Lab Task 3 (Linear Algebra operations in Python)

Import relevant libraries

In [29]:
import numpy as np
from numpy import random
import matplotlib.pyplot as plt

Create Random Vector

In [311]:
x=1
y=1

arr1 = random.randint(10, size = (2)).reshape(-1,1)

while (arr1[0]==0 and arr1[1]==0):
    arr1 = random.randint(10, size = (2)).reshape(1,-1)
    
arr2 = random.randint(10, size = (2))

print(arr1)
print(arr2)

[[2]
 [5]]
[4 6]


In [312]:
def ga(a1, a2):
    
    while (a2[0] == 0 and a2[1]==0):
        a2 = random.randint(10, size = (2))
        print(np.dot(a1, a2.T))
    return a2

In [313]:
arr2 = ga(arr1, arr2)

In [316]:
print(arr1)
print(arr2)

[[2]
 [5]]
[4 6]


In [315]:
np.rot90(arr1, k=1)

array([[2, 5]])

In [318]:
import pandas as pd
df = pd.read_csv("iris.csv")

In [319]:
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]